### ISSUE TITLE
Camera near pole causes OutOfMemoryError

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#116]
Placing the camera near either pole and zooming in eventually results in an OutOfMemoryError.

java.lang.OutOfMemoryError: Failed to allocate a 13884 byte allocation with 13520 free bytes and 13KB until OOM
      at gov.nasa.worldwind.globe.BasicTessellator.prepareTile(BasicTessellator.java:197)
      at gov.nasa.worldwind.globe.BasicTessellator.addTile(BasicTessellator.java:150)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:139)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.addTileOrDescendants(BasicTessellator.java:144)
      at gov.nasa.worldwind.globe.BasicTessellator.assembleTiles(BasicTessellator.java:118)
      at gov.nasa.worldwind.globe.BasicTessellator.tessellate(BasicTessellator.java:97)
      at gov.nasa.worldwind.BasicFrameController.renderFrame(BasicFrameController.java:36)
      at gov.nasa.worldwind.WorldWindow.renderFrame(WorldWindow.java:941)
      at gov.nasa.worldwind.WorldWindow.doFrame(WorldWindow.java:678)
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
      at android.view.Choreographer.doFrame(Choreographer.java:549)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:135)
      at android.app.ActivityThread.main(ActivityThread.java:5297)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by pdavidc** [comment]
Memory usage investigation performed for #116 revealed that excessive tile count is the underlying cause of these out of memory errors. Near the poles, the number of terrain tiles or image tiles can exceed 5000 before the Android runtime runs out of memory. WorldWind is tuned to operate with between 10 and 100 tiles.

**Comment by pdavidc** [comment]
The tile selection algorithm, while otherwise well designed, uses a tile's height to determine whether or not to increase detail. Using height ignores the important detail that tiles near the poles are very distorted, and while height is an easy to understand constant, tile width varies both with level and with latitude.

More work is needed to refine WorldWind's operation near the poles. As an immediate solution to OutOfMemoryErrors at the poles, we have modified the tile selection algorithm to choose tile detail based on a tile's centroid width, rather than its height. Since the tile width varies with latitude, tile count near the poles remains reasonable.
