### ISSUE TITLE
 java.lang.IllegalArgumentException: No configs match configSpec

### ISSUE THREAD

**Issue by spyhunter99** [NASAWorldWind/WorldWindAndroid#5]
Attempting to run WWA on an API23 emulator and ran into this error message.

````
 java.lang.IllegalArgumentException: No configs match configSpec
                                                                     at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:859)
                                                                     at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
                                                                     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
                                                                     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
````

it's probably an emulator thing, but I'd suggest at least trying to trap the error message and report to the user that the device isn't supported.

**Comment by pdavidc** [comment]
Thanks for the suggestion! It's on our list to review the built-in GLSurfaceView configuration chooser, and we'll include this in that task
