### ISSUE TITLE
Replacement for default EGL config chooser

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#57]
The default EGL config chooser supplied by Android's GLSurfaceView can be error prone. The following stack trace is reproducible in environments that support the minimum requirements for WorldWindow:

E/AndroidRuntime(12715): FATAL EXCEPTION: GLThread 141
E/AndroidRuntime(12715): Process: gov.nasa.worldwindx.examples, PID: 12715
E/AndroidRuntime(12715): java.lang.IllegalArgumentException: No config chosen
E/AndroidRuntime(12715):     at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:874)
E/AndroidRuntime(12715):     at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
E/AndroidRuntime(12715):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
E/AndroidRuntime(12715):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

Investigate this issue and provide a more suitable default EGL config chooser for WorldWindow. An example implementation is attached.
[configChooser.patch.zip](https://github.com/NASAWorldWind/WorldWindAndroid/files/446074/configChooser.patch.zip)

**Comment by Sufaev** [comment]
This patch is really useful, especially when you want to show camera preview on the background.

Now WorldWindow use RGB_565 color format by default and thats why globe background is opaque black.

Current fix of this problem require custom EGLConfigurator class to be passed in WorldWinf constructor.

It will be good to have transparent background by default.

I simplified your class:
public class WWConfigChooser implements GLSurfaceView.EGLConfigChooser {
    private int config_size = 64;

    @Override
    public EGLConfig chooseConfig(EGL10 egl, EGLDisplay display) {
        int[] attrib_list = {
                EGL10.EGL_RED_SIZE, 8,
                EGL10.EGL_GREEN_SIZE, 8,
                EGL10.EGL_BLUE_SIZE, 8,
                EGL10.EGL_ALPHA_SIZE, 8,
                EGL10.EGL_DEPTH_SIZE, 16,
                EGL10.EGL_NONE
        };

        EGLConfig[] configs = new EGLConfig[config_size];
        int[] num_config = new int[1];
        if (!egl.eglChooseConfig(display, attrib_list, configs, config_size, num_config)) {
            throw new IllegalArgumentException("eglChooseConfig failed");
        }
        config_size = num_config[0];

        EGLConfig config = config_size > 0 ? configs[0] : null;
        if (config == null) {
            throw new IllegalArgumentException("No config chosen");
        }

        return config;
    }

}
