### ISSUE TITLE
WMS GLUtils.getType throws IllegalArgumentException: Unknown type

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindAndroid#67]
A client reported a exception when accessing a World Wind WMS.  The following log was provided.  It appears the client is accessing a WMS and loading the result into a surface image.

```
09-29 22:54:04.556  1485  1588 E gov.nasa.worldwind: Image retrieval failed with exception 'http://worldwind25.arc.nasa.gov/wms?SERVICE=WMS&VERSION=1.1&REQUEST=GetMap&LAYERS=BlueMarble-200412&STYLES=&SRS=EPSG:4326&BBOX=<hidden>&WIDTH=256&HEIGHT=256&FORMAT=image/png&TRANSPARENT=TRUE'
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind: RenderableLayer.doRender: Exception while rendering shape 'Surface Image'
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind: java.lang.IllegalArgumentException: Unknown type
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.opengl.GLUtils.getType(GLUtils.java:71)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.render.Texture.<init>(Texture.java:48)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.render.RenderResourceCache.retrieveTexture(RenderResourceCache.java:146)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.render.RenderContext.retrieveTexture(RenderContext.java:399)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.shape.SurfaceImage.doRender(SurfaceImage.java:85)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.render.AbstractRenderable.render(AbstractRenderable.java:88)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.layer.RenderableLayer.doRender(RenderableLayer.java:214)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.layer.AbstractLayer.render(AbstractLayer.java:134)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.BasicFrameController.renderLayers(BasicFrameController.java:83)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.BasicFrameController.renderFrame(BasicFrameController.java:44)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.WorldWindow.renderFrame(WorldWindow.java:912)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at gov.nasa.worldwind.WorldWindow.doFrame(WorldWindow.java:656)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.view.Choreographer.doFrame(Choreographer.java:603)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.os.Handler.handleCallback(Handler.java:739)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.os.Handler.dispatchMessage(Handler.java:95)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.os.Looper.loop(Looper.java:148)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at android.app.ActivityThread.main(ActivityThread.java:5422)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at java.lang.reflect.Method.invoke(Native Method)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 22:54:04.571  1485  1485 E gov.nasa.worldwind:
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-29 22:54:04.571  1485  1588 E gov.nasa.worldwind: Image retrieval failed with exception 'http://worldwind25.arc.nasa.gov/wms?SERVICE=WMS&VERSION=1.1&REQUEST=GetMap&LAYERS=BlueMarble-200412&STYLES=&SRS=EPSG:4326&BBOX=<hidden>&WIDTH=256&HEIGHT=256&FORMAT=image/png&TRANSPARENT=TRUE'
```

**Comment by emxsys** [comment]
I've been unable to replicate this error with either a malformed URL or a disconnected network.  I suspect an issue with the hardware configuration.
